# tox (https://tox.readthedocs.io/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

# Meaningless change

[tox]
envlist = py{311}

[testenv]
allowlist_externals = rm
deps =
    -r requirements.txt
    bandit[toml]
    pytest
    twine
    build
commands =
    rm -f {toxinidir}/dist/*
    bandit -r {toxinidir}/src
    pytest
    python -m build --outdir {toxinidir}/dist {toxinidir}
    twine upload -r dhpypi dist/* --verbose
package = wheel
